version: "3.5"
services:
  copybara:
    platform: linux/amd64
    image: getty708/copybara:20240104-5e3d88cf-gha
    tty: true
    environment:
      OPYBARA_SUBCOMMAND: migrate
      COPYBARA_CONFIG: copy.bara.sky
      COPYBARA_WORKFLOW: default
      COPYBARA_SOURCEREF: ""
      COPYBARA_OPTIONS: "--force"
    volumes:
      - ./:/usr/src/app
      - ${GIT_CONFIG_PATH}:/root/.gitconfig:ro
      - ${GIT_CREDENTIALS_PATH}:/root/.git-credentials:ro
      - ${SSH_KEY_PATH}:/root/.ssh/id_git
      - ${SSH_KNOWN_HOSTS_PATH}:/root/.ssh/known_hosts

