name: Sync OpenPack Documentation

on:
  push:
    branches:
      - "main"
      - "feat/getty708/**"
jobs:
  move-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - run: |
          mkdir ~/.ssh
          chmod 700 ~/.ssh
          echo $'${{ secrets.SSH_CONFIG }}' > ~/.ssh/config
          chmod 600 ~/.ssh/config
          echo $'${{ secrets.SSH_KEY }}' > ~/.ssh/id_git
          chmod 600 ~/.ssh/id_git
          echo $'${{ secrets.SSH_KNOWN_HOSTS }}' > ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts
          echo $'${{ secrets.GIT_CREDENTIALS }}' > ~/.git-credentials
        shell: bash

      # Create .env file
      - run: |
          echo "GIT_CONFIG_PATH=~/.gitconfig" >> .env
          echo "GIT_CREDENTIALS_PATH=~/.git-credentials" >> .env
          echo "SSH_CONFIG_PATH=~/.ssh/config" >> .env
          echo "SSH_KEY_PATH=~/.ssh/id_git" >> .env
          echo "SSH_KNOWN_HOSTS_PATH=~/.ssh/known_hosts" >> .env
        shell: bash

      - run: |
          git config --global user.name ${{ secrets.GIT_NAME }}
          git config --global user.email ${{ secrets.GIT_EMAIL }}
        shell: bash

      - run: |
          ls -la ~
          ls -la ~/.ssh
        shell: bash

      - run: docker pull getty708/copybara:20230105-5e3d88cf
        shell: bash

      - run: docker compose up
        shell: bash
  