name: Sync OpenPack Documentation

on:
  push:
    branches:
      - "main"
      - "feat/getty708/**"
jobs:
  move-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Setup SSH
        env:
          SSH_CONFIG: ${{ secrets.SSH_CONFIG }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
          GIT_CREDENTIALS: ${{ secrets.GIT_CREDENTIALS }}
        run: |
          mkdir ~/.ssh
          echo "$SSH_CONFIG" > ~/.ssh/config
          echo "$SSH_KEY" > ~/.ssh/id_git
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
          echo "$GIT_CREDENTIALS" > ~/.git-credentials
        shell: bash

      # Create .env file
      - run: |
          echo "GIT_CONFIG_PATH=~/.gitconfig" >> .env
          echo "GIT_CREDENTIALS_PATH=~/.git-credentials" >> .env
          echo "SSH_CONFIG_PATH=~/.ssh/config" >> .env
          echo "SSH_KEY_PATH=~/.ssh/id_git" >> .env
          echo "SSH_KNOWN_HOSTS_PATH=~/.ssh/known_hosts" >> .env
        shell: bash

      - run: |
          git config --global user.name ${{ secrets.GIT_NAME }}
          git config --global user.email ${{ secrets.GIT_EMAIL }}
        shell: bash

      - name: for debug
        run: |
          ls -la ~
          ls -la ~/.ssh
          ls -la ./
          cat ~/.ssh/config
          cat ~/.ssh/known_hosts
        shell: bash

      - run: docker pull getty708/copybara:20230105-5e3d88cf
        shell: bash

      - run: docker compose up
        shell: bash
  